version: 2.1
jobs:
  pr-check:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers # Primary container image where all commands run
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram # Service container image
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: pip install --upgrade pip --user
      - run: pip3 install -r requirements.txt
      - run: |
          psql CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      - run: |
          psql -d $TEST_DATABASE_URL -c "CREATE TABLE test (id char(40), first_name char(25),  last_name char(25), email_address char(22), password char(20), account_created timestamp, account_updated timestamp);"
      - run: |
          psql -d $TEST_DATABASE_URL -c "INSERT INTO test VALUES (uuid_generate_v4(), 'Maeve', 'Wile', 'maeve@wiley.com', 'Maeve$Wiley123', now(), now()), (uuid_generate_v4(), 'Jenny', 'Lopez', 'jenny@lopez.com', 'Jenny$Lopez123', now(), now());"
      - run: |
          psql -d $TEST_DATABASE_URL -c "SELECT * from test;"
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers # Primary container image where all commands run
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram # Service container image
    steps:
      - checkout
workflows:
  version: 2.1
  pr-check-and-build:
    jobs:
    - pr-check
    - build
